apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - image: colbyx20/web-server:1.0.5
          name: web-server
          resources:
            requests:
              memory: "150Mi"
              cpu: "100m"
            limits:
              memory: "550Mi"
              cpu: "150m"
