apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
    #   nginx.ingress.kubernetes.io/configuration-snippet: |
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    name: ingress
    namespace: dev
    resourceVersion: "342054"
  spec:
    ingressClassName: traefik
    rules:
    - host: api-dev-local
      http:
        paths:
        - backend:
            service:
              name: web-app-dev
              port:
                number: 80
          path: /
          pathType: Prefix
    - host: api-sit-local
      http:
        paths:
        - backend:
            service:
              name: web2
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 172.18.0.2
      - ip: 172.18.0.3
      - ip: 172.18.0.4
kind: List
metadata:
  resourceVersion: ""
