apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app
  name: web-app-dev
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web-app
  type: ClusterIP
