apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: dev
type: Opaque
stringData:
  pghost: "postgres.database.svc.cluster.local"
  pgport: "5432"
  pguser: "testuser"
  pgpass: "testpass"
  pgdb: "testdb"
