apiVersion: v1
kind: Service
metadata:
  name: app-svc-dev
  namespace: dev
spec:
  selector:
    app: app-dev
    env: dev
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
